// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLOSbyq_3fBGu8-iFx7udMAz8IVF2iN4g',
    appId: '1:682052365327:web:0c1f1bef5103db82f8c77a',
    messagingSenderId: '682052365327',
    projectId: 'tuition-app-181c4',
    authDomain: 'tuition-app-181c4.firebaseapp.com',
    storageBucket: 'tuition-app-181c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-PmIQdtIftE609vkPmsYNAXhtDJ1Ipb0',
    appId: '1:682052365327:android:acda74719416c542f8c77a',
    messagingSenderId: '682052365327',
    projectId: 'tuition-app-181c4',
    storageBucket: 'tuition-app-181c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJsSCaTNb8YiYwtLwirq919zsXgP6ySSM',
    appId: '1:682052365327:ios:c625894a850dc4cef8c77a',
    messagingSenderId: '682052365327',
    projectId: 'tuition-app-181c4',
    storageBucket: 'tuition-app-181c4.appspot.com',
    iosClientId: '682052365327-ov2kfsu2m0u0785m1mkpn6r77h13gvb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuitionAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJsSCaTNb8YiYwtLwirq919zsXgP6ySSM',
    appId: '1:682052365327:ios:c625894a850dc4cef8c77a',
    messagingSenderId: '682052365327',
    projectId: 'tuition-app-181c4',
    storageBucket: 'tuition-app-181c4.appspot.com',
    iosClientId: '682052365327-ov2kfsu2m0u0785m1mkpn6r77h13gvb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuitionAppProject',
  );
}
